services:
  app:
    image: node:16  # Utilise l'image Node.js
    container_name: codepromopropfirm_app
    working_dir: /codepromopropfirm  # Définit le répertoire de travail dans le conteneur
    volumes:
      - .:/codepromopropfirm  # Monte le répertoire local dans /codepromopropfirm dans le conteneur
      - /codepromopropfirm/node_modules  # Empêche node_modules d'être écrasé
    environment:
      - NODE_ENV=production
    ports:
      - "3000:3000"  # Mappe le port 3000 pour accéder à ton application
    command: bash -c "npm install && npm start"
